# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7Qmos8Sh3nzhhBS1VuC4uWeRj557qq1
"""

def get_user_text():
    text = input("Matn kiriting: ")
    return text

def count_words(text):
    words = text.split()
    return len(words)
def main():
    text = get_user_text()
    word_count = count_words(text)

    print(f"\nMatndagi jami so'zlar soni: {word_count}")

main()

